import { textDecoder } from '@/str';
import type { BaseX } from '../basex';

var ALPHABET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
var ENCODE_TABLE = new TextEncoder().encode(ALPHABET);
var DECODE_TABLE = new Uint8Array(128).fill(255);
for (let i = 0; i < ENCODE_TABLE.length; ++i) {
  DECODE_TABLE[ENCODE_TABLE[i]] = i;
}

var DECODE_ENTRIES = new Uint16Array(128).fill(0xffff);
for (let i = 0; i < ENCODE_TABLE.length; ++i) {
  DECODE_ENTRIES[ENCODE_TABLE[i]] = i | (((i & 0x1e) === 0x1e ? 5 : 6) << 8);
}

var LOG2_TABLE = new Uint8Array(62);
LOG2_TABLE[0] = 1;
for (let i = 1; i < 62; ++i) {
  LOG2_TABLE[i] = Math.ceil(Math.log2(i + 1));
}

var PAIR_TABLE = new Uint32Array(4096);
for (let v = 0; v < 4096; ++v) {
  let c0 = v & 0x3f;
  let s0 = 6;
  if ((c0 & 0x1e) === 0x1e) {
    c0 &= 0x1f;
    s0 = 5;
  }
  let c1 = (v >> s0) & 0x3f;
  let s1 = 6;
  if ((c1 & 0x1e) === 0x1e) {
    c1 &= 0x1f;
    s1 = 5;
  }
  PAIR_TABLE[v] =
    ENCODE_TABLE[c0] | (ENCODE_TABLE[c1] << 8) | ((s0 + s1) << 16);
}

var ENCODE_BUFFER_SIZE = 2048;
var encodeBuffer = new Uint8Array(ENCODE_BUFFER_SIZE);

/**
 * Base62-like encoder/decoder for binary data but **super fast**. Useful for human readable tokens generation
 *
 * **Warning!** Not RFC standard
 *
 * @example Basic usage
 * ```typescript
 * const data = new Uint8Array([255, 128, 64]);
 * const encoded = base62.encode(data);
 * console.log(encoded);
 *
 * const decoded = base62.decode(encoded);
 * console.log(decoded); // Uint8Array [255, 128, 64]
 * ```
 *
 * @example Text encoding
 * ```typescript
 * const text = "Hello World!";
 * const bytes = new TextEncoder().encode(text);
 * const encoded = base62.encode(bytes);
 * const decoded = base62.decode(encoded);
 * const result = new TextDecoder().decode(decoded);
 * console.log(result); // "Hello World!"
 * ```
 *
 * @group Binary
 */
export const base62Fast: BaseX = {
  alphabet: ALPHABET,
  padding: '',

  /**
   * Encodes a Uint8Array into a Base62 string using a custom 5/6-bit variable length scheme.
   * Processes bits from left to right maintaining correct order.
   * @param input The Uint8Array to encode.
   * @returns The encoded Base62 string.
   */
  encode(input: Uint8Array): string {
    var inputLength = input.length;
    var need = (((inputLength * 8) / 5) | 0) + 4;
    var output =
      need <= ENCODE_BUFFER_SIZE ? encodeBuffer : new Uint8Array(need);
    var outputIndex = 0;
    var remainingBits = inputLength * 8;
    var inputIndex = 0;
    var buffer = 0;
    var bitPosition = 0;
    var pair;
    var chunkSize;
    var value;

    while (remainingBits > 20) {
      if (bitPosition < 12) {
        buffer |=
          (input[inputIndex] | (input[inputIndex + 1] << 8)) << bitPosition;
        inputIndex += 2;
        bitPosition += 16;
      }
      pair = PAIR_TABLE[buffer & 0xfff];
      output[outputIndex] = pair;
      output[outputIndex + 1] = pair >> 8;
      outputIndex += 2;
      chunkSize = pair >> 16;
      buffer >>= chunkSize;
      bitPosition -= chunkSize;
      remainingBits -= chunkSize;
    }

    while (remainingBits > 6) {
      if (bitPosition < 6) {
        buffer |= input[inputIndex++] << bitPosition;
        bitPosition += 8;
      }
      value = buffer & 0x3f;
      if ((value & 0x1e) === 0x1e) {
        value &= 0x1f;
        buffer >>= 5;
        bitPosition -= 5;
        remainingBits -= 5;
      } else {
        buffer >>= 6;
        bitPosition -= 6;
        remainingBits -= 6;
      }
      output[outputIndex++] = ENCODE_TABLE[value];
    }

    if (remainingBits > 0) {
      if (buffer > 0x3d) {
        output[outputIndex++] = ENCODE_TABLE[buffer & 0x1f];
        buffer >>= 5;
      }
      output[outputIndex++] = ENCODE_TABLE[buffer];
    }

    return textDecoder.decode(output.subarray(0, outputIndex));
  },

  /**
   * Decodes a Base62 string generated by the custom encoder back into a Uint8Array.
   * @param input The Base62 string to decode.
   * @returns The decoded Uint8Array.
   */
  decode(input: string): Uint8Array {
    var inputLength = input.length;
    var output = new Uint8Array(((inputLength * 6) >> 3) + 5);
    var writeIndex = 0;
    var bitPosition = 0;
    var buffer = 0;
    var readIndex = 0;
    var lastIndex = inputLength - 1;
    var quadEnd = lastIndex - 3;
    var e0;
    var e1;
    var e2;
    var e3;
    var s0;
    var s1;
    var s2;
    var fullBits;
    var value;

    while (readIndex < quadEnd) {
      e0 = DECODE_ENTRIES[input.charCodeAt(readIndex)];
      e1 = DECODE_ENTRIES[input.charCodeAt(readIndex + 1)];
      e2 = DECODE_ENTRIES[input.charCodeAt(readIndex + 2)];
      e3 = DECODE_ENTRIES[input.charCodeAt(readIndex + 3)];
      if (!(e0 < 0x700 && e1 < 0x700 && e2 < 0x700 && e3 < 0x700)) {
        throwInvalid(input, readIndex);
      }
      readIndex += 4;
      s0 = e0 >> 8;
      s1 = s0 + (e1 >> 8);
      s2 = s1 + (e2 >> 8);
      buffer |=
        ((e0 & 0xff) |
          ((e1 & 0xff) << s0) |
          ((e2 & 0xff) << s1) |
          ((e3 & 0xff) << s2)) <<
        bitPosition;
      bitPosition += s2 + (e3 >> 8);
      output[writeIndex] = buffer;
      output[writeIndex + 1] = buffer >> 8;
      output[writeIndex + 2] = buffer >> 16;
      fullBits = (bitPosition >> 3) << 3;
      writeIndex += fullBits >> 3;
      buffer >>= fullBits;
      bitPosition -= fullBits;
    }

    while (readIndex < lastIndex) {
      e0 = DECODE_ENTRIES[input.charCodeAt(readIndex)];
      if (!(e0 < 0x700)) {
        throwInvalid(input, readIndex);
      }
      readIndex++;
      buffer |= (e0 & 0xff) << bitPosition;
      bitPosition += e0 >> 8;
      output[writeIndex] = buffer;
      fullBits = (bitPosition >> 3) << 3;
      writeIndex += fullBits >> 3;
      buffer >>= fullBits;
      bitPosition -= fullBits;
    }

    if (inputLength > 0) {
      value = DECODE_TABLE[input.charCodeAt(lastIndex)];
      if (!(value < 62)) {
        throwInvalid(input, lastIndex);
      }
      buffer |= value << bitPosition;
      bitPosition += LOG2_TABLE[value];
    }

    if (bitPosition >= 8) {
      output[writeIndex++] = buffer & 0xff;
      buffer >>= 8;
      bitPosition -= 8;
    }
    if (bitPosition > 0) {
      output[writeIndex++] = buffer & 0xff;
    }

    return output.subarray(0, writeIndex);
  },
};

function throwInvalid(input: string, from: number): never {
  for (var readIndex = from; readIndex < input.length; readIndex++) {
    if (!(DECODE_TABLE[input.charCodeAt(readIndex)] < 62)) {
      throw new Error(
        'Invalid Base62 input: contains non-alphabet characters. Index: ' +
          readIndex,
      );
    }
  }
  throw new Error('Invalid Base62 input: contains non-alphabet characters.');
}
